services:
  postgres:
    image: postgres:latest
    container_name: to-do-postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
